version: "3"

services:
  scrapper:
    env_file: .env
    build:
      context: .
    container_name: healthcheck_scrapper
    volumes:
      - ./spiders:/project/spiders
      - ./plays:/project/plays
    tty: true

  archiver:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.archiver
    container_name: healthcheck_archiver
    tty: true
