version: "3"

services:
  scrapper:
    env_file: .env
    build:
      context: .
    container_name: healthcheck_scrapper
    volumes:
      - ./spiders:/project/spiders
      - ./plays:/project/plays
    tty: true
    depends_on:
      - db

  archiver:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.archiver
    container_name: healthcheck_archiver
    tty: true
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: healthcheck_db
    env_file: ./docker/.env-postgres
    ports:
      - "15433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
