version: "3"

services:
  scraper:
    env_file: .env
    build:
      context: .
    container_name: healthcheck_scraper
    volumes:
      - ./sessions/:/project/sessions/
    tty: true
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: healthcheck_db
    env_file: ./docker/.env-postgres
    ports:
      - "15433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
