version: "3"

services:
  scraper:
    env_file: .env
    build:
      context: .
    container_name: healthcheck_scraper
    volumes:
      - ./sessions/:/project/sessions/
      - ./logs/:/var/log/
    tty: true
    depends_on:
      - db
      - tor

  tor:
    build:
      context: .
      dockerfile: Dockerfile.tor
    container_name: healthcheck_tor
    restart: always
    ports:
      - "9050:9050"
      - "9051:9051"
  db:
    image: postgres:16
    container_name: healthcheck_db
    env_file: ./docker/.env-postgres
    ports:
      - "15433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
